language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
before_install:
  - sudo apt-get update
  - sudo apt-get --no-install-recommends install tracker gir1.2-tracker-0.10 libtracker-sparql-0.10-dev
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "DISPLAY=:99.0 bundle exec rake test"
