sudo: required
dist: trusty
language: ruby

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgirepository1.0-dev gobject-introspection
  - sudo apt-get install -y gir1.2-tracker-0.16 libtracker-sparql-0.16-dev
  - sudo apt-get --no-install-recommends install -y tracker

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.1
  - ruby-head
  - ruby-head-clang
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: ruby-head-clang

# Tests must be run with an X-server to allow D-Bus autolaunch, which
# Tracker needs.
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "DISPLAY=:99.0 bundle exec rake test"
