language: ruby

dist: xenial

services:
  - xvfb

before_install:
  - sudo apt-get update
  # Provides libgirepository-1.0.so.1
  - sudo apt-get install libgirepository-1.0-1
  # Provides Tracker-1.0.typelib
  - sudo apt-get install gir1.2-tracker-1.0
  # Provides libtracker-sparql-1.0.so
  - sudo apt-get install libtracker-sparql-1.0-dev
  # Sets up a mimimal tracker installation
  - sudo apt-get --no-install-recommends install -y tracker

cache:
  bundler: true

script: bundle exec rake

jobs:
  include:
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: jruby-9.2
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: 2.7.1
      name: "RuboCop"
      before_install: []
      script: bundle exec rubocop
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

branches:
  only:
    - master
