language: ruby
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
  - ruby-head-clang
  - jruby-9.0
  - jruby-head
  - rbx-3.7
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: ruby-head-clang
before_install:
  - sudo apt-get update
  - sudo apt-get --no-install-recommends install tracker gir1.2-tracker-0.14 libtracker-sparql-0.14-dev libgirepository1.0-dev gobject-introspection
# Tests must be run with an X-server to allow D-Bus autolaunch, which
# Tracker needs.
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "DISPLAY=:99.0 bundle exec rake test"
